### ISSUE TITLE
AttributeError: module 'modules.functional' has no attribute 'furthest_point_sampling'

### ISSUE THREAD

**Issue by Prominem** [mit-han-lab/pvcnn#5]
Can this code be run with cuda-9.2? modules.functional doesn't work on my machine with cuda-9.2

**Comment by synxlin** [comment]
Hi, @Prominem. Could you please provide detailed error information?
By the way, our experiments are all conducted on PyTorch 1.3.1 + CUDA 10.0/10.1.

**Comment by Prominem** [comment]
thanks for replying, @synxlin I solve this problem by restarting my computer.
